[package]
name = "mike_mark_random_walker"
version = "0.1.0"
authors = ["Mark Lodato <mark@gnar.dog>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
